name: assignment4

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      
      - name: Build stocks service with Maven
        working-directory: ./stocks
        run: mvn clean package -DskipTests
      
      - name: Build capital gains service with Maven
        working-directory: ./capitalgains
        run: mvn clean package -DskipTests
      
      - name: Build stocks service Docker image
        working-directory: ./stocks
        run: docker build -t ci-cd-stocks1 .
      
      - name: Build capital gains service Docker image
        working-directory: ./capitalgains
        run: docker build -t ci-cd-capital-gains .
      
      - name: Save Docker images
        run: |
          docker save ci-cd-stocks1 > stocks-service.tar
          docker save ci-cd-capital-gains > capital-gains-service.tar
      
      - name: Upload Docker images as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: docker-images
          path: |
            stocks-service.tar
            capital-gains-service.tar

  test:
    needs: build
    runs-on: ubuntu-24.04
    services:
      mongo:
        image: mongo:5.0
        ports:
          - 27017:27017
    steps:
      - uses: actions/checkout@v4
      
      - name: Download Docker images
        uses: actions/download-artifact@v4
        with:
          name: docker-images
      
      - name: Load Docker images
        run: |
          docker load < stocks-service.tar
          docker load < capital-gains-service.tar
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest requests pymongo
      
      - name: Start services
        run: |
          docker compose up -d --no-build
          sleep 30
      
      - name: Run tests
        run: |
          pytest -v tests/assn4_tests.py | tee assn4_test_results.txt
        continue-on-error: true
      
      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: assn4_test_results.txt
      
      - name: Stop services
        run: docker compose down

  query:
    needs: test
    runs-on: ubuntu-24.04
    services:
      mongo:
        image: mongo:5.0
        ports:
          - 27017:27017
    steps:
      - uses: actions/checkout@v4
      
      - name: Download Docker images
        uses: actions/download-artifact@v4
        with:
          name: docker-images
      
      - name: Load Docker images
        run: |
          docker load < stocks-service.tar
          docker load < capital-gains-service.tar
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pymongo
      
      - name: Start services
        run: |
          docker compose up -d --no-build
          sleep 30
      
      - name: Run queries
        run: python tests/query_executor.py
      
      - name: Upload response file
        uses: actions/upload-artifact@v4
        with:
          name: query-results
          path: response.txt
      
      - name: Stop services
        run: docker compose down
