name: assignment4

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Build stocks service
        run: |
          cd stocks
          docker build -t stocks-service .
      
      - name: Build capital gains service
        run: |
          cd capitalgains
          docker build -t capital-gains-service .
      
      - name: Save Docker images
        run: |
          docker save stocks-service > stocks-service.tar
          docker save capital-gains-service > capital-gains-service.tar
      
      - name: Upload Docker images as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: docker-images
          path: |
            stocks-service.tar
            capital-gains-service.tar

  test:
    needs: build
    runs-on: ubuntu-latest
    services:
      mongo:
        image: mongo:5.0
        ports:
          - 27017:27017
    steps:
      - uses: actions/checkout@v4
      
      - name: Download Docker images
        uses: actions/download-artifact@v4
        with:
          name: docker-images
      
      - name: Load Docker images
        run: |
          docker load < stocks-service.tar
          docker load < capital-gains-service.tar
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest requests
      
      - name: Start services
        run: |
          docker compose up -d
          sleep 30  # Wait for services to be ready
      
      - name: Run tests
        run: |
          pytest -v tests/assn4_tests.py | tee assn4_test_results.txt
        continue-on-error: true
      
      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: assn4_test_results.txt
      
      - name: Stop services
        run: docker compose down

  query:
    needs: test
    runs-on: ubuntu-latest
    services:
      mongo:
        image: mongo:5.0
        ports:
          - 27017:27017
    steps:
      - uses: actions/checkout@v4
      
      - name: Download Docker images
        uses: actions/download-artifact@v4
        with:
          name: docker-images
      
      - name: Load Docker images
        run: |
          docker load < stocks-service.tar
          docker load < capital-gains-service.tar
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
      
      - name: Start services
        run: |
          docker compose up -d
          sleep 30  # Wait for services to be ready
      
      - name: Run queries
        run: python tests/query_executor.py
      
      - name: Upload response file
        uses: actions/upload-artifact@v4
        with:
          name: query-results
          path: response.txt
      
      - name: Stop services
        run: docker compose down
